language: go

services:
  - redis-server

env:
- GOFILES=$(find . -type f -name '*.go' -not -path "./vendor/*")
- GOPACKAGES=$(go list ./... | grep -v /vendor/)

script:
- goimports -d $GOFILES | tee | read && echo "Please run goimports to fix the code style" 1>&2 && false
- gometalinter --vendor --disable-all --enable=vet --enable=vetshadow --enable=golint --enable=ineffassign --enable=goconst --tests ./...
- go test $GOPACKAGES
